// Code generated by goctl. DO NOT EDIT.
// Source: rpctest.proto

package server

import (
	"context"

	"rpctest/internal/logic"
	"rpctest/internal/svc"
	"rpctest/rpctest"
)

type RpctestServer struct {
	svcCtx *svc.ServiceContext
	rpctest.UnimplementedRpctestServer
}

func NewRpctestServer(svcCtx *svc.ServiceContext) *RpctestServer {
	return &RpctestServer{
		svcCtx: svcCtx,
	}
}

func (s *RpctestServer) Ping(ctx context.Context, in *rpctest.Request) (*rpctest.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
